CC=gcc
CFLAGS=-I.

all: sequential_min_max parallel_min_max exec_seq_min_max libutils.a

sequential_min_max : utils.o find_min_max.o utils.h find_min_max.h
	$(CC) -o sequential_min_max find_min_max.o utils.o sequential_min_max.c $(CFLAGS)

parallel_min_max : utils.o find_min_max.o utils.h find_min_max.h
	$(CC) -o parallel_min_max utils.o find_min_max.o parallel_min_max.c $(CFLAGS)

exec_seq_min_max : utils.o find_min_max.o
	$(CC) -o exec_sequential exec_seq_min_max.c utils.o find_min_max.o $(CFLAGS)

libutils.a: utils.o
	ar rcs libutils.a utils.o

utils.o : utils.h
	$(CC) -o utils.o -c utils.c $(CFLAGS)

find_min_max.o : utils.h find_min_max.h
	$(CC) -o find_min_max.o -c find_min_max.c $(CFLAGS)

clean :
	rm -f utils.o find_min_max.o sequential_min_max parallel_min_max exec_seq_min_max libutils.a